#!/bin/bash
set -euv

http_server=$(cat /proc/cmdline | sed -e 's/^.*xmr_stak_http_srv=//' -e 's/ .*$//')

cd /tmp
rm *.txt
lscpu -J > lscpu.txt
! curl -Lf -o config.txt --data "@lscpu.txt" $http_server/xmr-stak/config.txt
! curl -Lf -o cpu.txt --data "@lscpu.txt" $http_server/xmr-stak/cpu.txt

[ ! -f config.txt ] && ! cp /etc/xmr-stak/config.txt .
[ ! -f cpu.txt ] && ! cp /etc/xmr-stak/cpu.txt .
