#!/bin/bash
set -euv

http_server=$(cat /proc/cmdline | sed -e 's/^.*xmr_stak_http_srv=//' -e 's/ .*$//')

echo "Fetching xmr-stak config from $http_server..."

cd /tmp
! rm *.txt
lscpu -J > lscpu.txt
! curl -Lf -o config.txt --data "@lscpu.txt" $http_server/config.txt
! curl -Lf -o cpu.txt --data "@lscpu.txt" $http_server/cpu.txt

[ ! -f config.txt ] && ! cp /etc/xmr-stak/config.txt .
[ ! -f cpu.txt ] && ! cp /etc/xmr-stak/cpu.txt .
